### ISSUE TITLE
Update for Breeze

### ISSUE THREAD

**Issue by Wierdio** [colinhartigan/valorant-rpc#24]

**Comment by Wierdio** [comment]
https://twitter.com/floxayyy/status/1387063329487785987

**Comment by Fablo020** [comment]
Thank you for that link. Now I just need to find out how to add the map picture (i added Foxtrot to the map list and added a squared and a "normal" picture to assets). Maybe I do something wrong because the Map Image doesn't show up on discord.
But I don't know much python, maybe I should wait for an update instead.

**Comment by colinhartigan** [comment]
working on the update right now

**Comment by colinhartigan** [comment]
see [v2.3](https://github.com/colinhartigan/valorant-rpc/releases/tag/v2.3)
