### ISSUE TITLE
Keeps waiting for Valorant to Launch, Eventually terminates

### ISSUE THREAD

**Issue by senaru** [colinhartigan/valorant-rpc#29]
I tried many methods to get it working, used the release 2.3 when it came out, tried reinstalling, tried building from source, tried running as admin, tried launching after game, gave up and waited patiently for 2.4 to release literally.... everything that came to my mind but I'm having trouble actually getting it to work.

What happens is the CLI runs and waits for the game to open, the game launches, but the rpc doesn't detect the game and eventually terminates itself due to "Valorant not running"

**Comment by didotb** [comment]
I've had the same issue. Neither I nor the owner knows what's the problem. I looked at the source, there's no problem at all.

I fixed it by cloning the git repo instead and added my own batch file program to execute the `main.py`.
I then created my own shortcut with the red icon located at the assets folder so I can open it via start menu

> Valorant-RPC.bat
```
@echo off
python .\main.py
```

### EDIT: Clarification
+ I didn't build from source after cloning since that also doesn't work for me
+ the `Valorant-RPC.bat` file is in the same folder as the `main.py` file
